"""SQLAlchemy 2.0 models for the Sales domain."""

from __future__ import annotations

from datetime import datetime

from sqlalchemy import BigInteger, DateTime, Identity, Integer, String, func
from sqlalchemy.orm import Mapped, mapped_column

from .database import Base


class Sale(Base):
    __tablename__ = "sales"

    # GENERATED BY DEFAULT AS IDENTITY: PostgreSQL assigns the id for normal
    # creation, but an explicit id (legacy import) is also accepted.
    id: Mapped[int] = mapped_column(
        BigInteger,
        Identity(always=False),
        primary_key=True,
    )

    # Logical reference to a user owned by the User Service.
    # There is deliberately NO ForeignKey here: it lives in another database.
    user_id: Mapped[int] = mapped_column(Integer, nullable=False, index=True)

    item_name: Mapped[str] = mapped_column(String(255), nullable=False)

    quantity: Mapped[int] = mapped_column(Integer, nullable=False)

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
    )
