"""create sales table

Revision ID: 0001
Revises:
Create Date: 2026-09-08

The `id` column is GENERATED BY DEFAULT AS IDENTITY so that:
  * normal creation lets PostgreSQL assign the id, and
  * legacy import can insert an explicit id.
See app/service.py::_sync_identity_sequence for how the sequence is realigned
after explicit-id inserts.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "sales",
        sa.Column(
            "id",
            sa.BigInteger(),
            sa.Identity(always=False),
            primary_key=True,
            nullable=False,
        ),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("item_name", sa.String(length=255), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("quantity > 0", name="ck_sales_quantity_positive"),
    )
    op.create_index("ix_sales_user_id", "sales", ["user_id"])


def downgrade() -> None:
    op.drop_index("ix_sales_user_id", table_name="sales")
    op.drop_table("sales")
